### ISSUE TITLE
Python error 

### ISSUE THREAD

**Issue by owaisaliwani** [gustavowillam/SmartMapPlugin#11]
An error has occurred while executing Python code: 

ValueError: range() arg 3 must not be zero 
Traceback (most recent call last):
  File "C:/Users/Administrator/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 1711, in pushButton_ImportQGIS_clicked
    ymarks=[i for i in range(int(self.Cord_Y_min),int(self.Cord_Y_max) , interval_y)]
ValueError: range() arg 3 must not be zero

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.18.3-Zürich Zürich, 735cc85be9 

Python Path:
C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python
C:/Users/Administrator/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Administrator/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Administrator/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Administrator\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms

**Comment by gustavogvp** [comment]
Também tive esse problema, conseguiu solucionar?

**Comment by gustavowillam** [comment]
This error is occurring because the variable ( interval_y) has a zero value. Probably because the latitude variation has a minimum value, close to zero. Please check the amplitude (see the minimum and maximum value) of the variation of your y-coordinate (latitude) in UTM.
A possible failure could be when converting from lat/long to UTM in QGIS.

**Comment by owaisaliwani** [comment]
Thank you sir. You have developed wonderful plugin. I corrected this error
by reprojecting data file.
