### ISSUE TITLE
TypeError: sort_values() got an unexpected keyword argument 'ignore_index' 

### ISSUE THREAD

**Issue by valeriavalonso** [gustavowillam/SmartMapPlugin#12]
Quando fui utilizar o plugin o QGIS me mostrou uma janela com o seguinte erro: 
![image](https://user-images.githubusercontent.com/92753301/137789661-944a1385-50bd-4f4c-80c9-4ed44ce2c188.png)
e o plugin não continua o processamento, as abas Grid e Interpolação ficam trancadas, não consigo acessar nenhuma opção. 
Revisei se meus dados estavam corretos e o shape era do tipo ponto e estava com o sistema de coordenadas UTM como manda o tutorial do professor. Preciso tomar mais algum cuidado para o processo correto dos dados? Tipo de variável na tabela de atributo, ou algo do gênero? 
Não entendo nada de programação, por isso estou perdida, obrigada desde já

**Comment by gustavowillam** [comment]
Olá!

Verifiquei que está utilizando a versão 3.10.2 do QGIS. 
Na versão 1.1 do Smart-Map fizemos algumas correções de erros, e passamos a utilizar uma função do python (sort_values) que utiliza um parâmetro chamado: ignore_index.
Entretanto esse parâmetro só está disponivel para uma biblioteca python (pandas) a partir da versão 1.0.0 dessa biblioteca. 
Logo, te sugiro atualizar para a ultima versão estável do QGIS 3.16.11 (https://qgis.org/downloads/QGIS-OSGeo4W-3.16.11-1-Setup-x86_64.exe) para corrigir esse problema de versão de biblioteca.
