### ISSUE TITLE
Couldn't load plugin 'Smart_Map' due to an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by ckilroy0** [gustavowillam/SmartMapPlugin#13]
Couldn't load plugin 'Smart_Map' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'PIL' 
Traceback (most recent call last):
  File "/app/share/qgis/python/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/saf000137/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/__init__.py", line 36, in classFactory
    from .Smart_Map import smart_map
  File "/app/share/qgis/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/saf000137/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/Smart_Map.py", line 71, in 
    from PIL import Image
  File "/app/share/qgis/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'PIL'

Python version: 3.8.8 (default, Nov 10 2011, 15:00:00) [GCC 10.2.0] 
QGIS version: 3.16.11-Hannover Hannover, 26cc1c76 

Python Path:
/app/share/qgis/python
/home/saf000137/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python
/home/saf000137/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins
/app/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/usr/lib/python3.8/site-packages
/app/lib/python3.8/site-packages
/app/lib/python3.8/site-packages/numpy-1.19.5-py3.8-linux-x86_64.egg
/app/lib/python3.8/site-packages/MarkupSafe-1.1.1-py3.8-linux-x86_64.egg
/home/saf000137/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python
/home/saf000137/Desktop

**Comment by ckilroy0** [comment]
Installed Pillow and upgraded to pillow-8.4.0. Reinstalled Smart_Map plug-in, still experiencing issue.

**Comment by herbertbuehl** [comment]
I had the same problem with QGIS versions 3.16.7. and 3.22.5 (on macOS Big Sur). After deleting all QGIS versions and reinstalling LTR 3.16.6 the plugin worked (with: pip3 install matplotlib sklearn pandas skipy).
