### ISSUE TITLE
Outline polygon function doesn't work with Multypoligons

### ISSUE THREAD

**Issue by dragonfly-lover** [gustavowillam/SmartMapPlugin#14]
Hallo @gustavowillam , i'm trying to use this plugin with kubuntu 21.04, qgis 3.16
Basically, i can point out two problems

I have installed not only recommended dependencies, but also pandas, scipy,  scikit-learn, scikit-fuzzy, pysal e pyKrige.

I have two possible bugs

1) when i import "Pluvio 2017" files it imports correctly, but when i try to use an outline polygon:

a) outline poligon is not imported correctly (it shows like a line and not like latium outline).
 
b) after import it wipes all imported data.

anyway when i try to launch interpolation it crashes suddenly

![imported pluvio](https://user-images.githubusercontent.com/36678626/144759422-0707e5a9-ef00-4ad7-a510-4e340f6ba382.png)
![latium](https://user-images.githubusercontent.com/36678626/144759425-bb492098-52c4-4b47-8851-528012782ebe.png)
![latium borders error](https://user-images.githubusercontent.com/36678626/144759437-77e57c12-1f64-4135-8ee7-c61873093488.png)
[Data.zip](https://github.com/gustavowillam/SmartMapPlugin/files/7656588/Data.zip)

**Comment by gustavowillam** [comment]
Hi! Looking at your contour polygon, I noticed that you have several smaller polygons in the southern part of the map.
Currently the plugin cuts to layers of the type polygons. In this case your layer is multpoligons.
I used your data and did the interpolation without using the contour polygon.
First, resize the maximum and minimum values of X and Y to have a greater coverage of the map as shown in the figure below.

![image](https://user-images.githubusercontent.com/42176577/144854306-f8688856-3a78-4cbd-93a8-79ee103fb14b.png)

Then perform the interpolation without the contour polygon. 

![image](https://user-images.githubusercontent.com/42176577/144854507-9326e5e4-5c30-4779-b996-4da395da1dd4.png)


With the map interpolated in QGIS, make the cut through the Menu (Raster -> Extraction -> Clip raster by Mask Layer)

![image](https://user-images.githubusercontent.com/42176577/144854756-29c8f40c-25f7-44cb-b0a1-1eae278cf2c0.png)

Here is the QGIS project with the data used

Thanks!


[ExampleQGIS.zip](https://github.com/gustavowillam/SmartMapPlugin/files/7661029/ExampleQGIS.zip)

**Comment by dragonfly-lover** [comment]
God bless you Gustavo! It works like a charm in the way you wrote me.
Your plugin deserves to be integrated in the qgis general workflow, so useful it is!

Just want to know what to do with the issue. In case someone uses a multypoligons crop layer there has to be at least a messagebox that explains why it can't be used. Would you prefer I change the title or close the comment and open another issue?

Many thanks again!

**Comment by gustavowillam** [comment]
Thanks a lot!
The plugin is constantly improving. In the next version, we intend to solve the issue of multiple polygons in the clipping of the interpolation areas.
You can change the title and close the comment, please.
