### ISSUE TITLE
validacao cruzada

### ISSUE THREAD

**Issue by Riviane** [gustavowillam/SmartMapPlugin#15]
Na hora de fazer o gráfico de validação cruzada a ordem de x e y está diferente do que deveria : valor observado x valor predito, seria um erro só no meu ou algo geral? tem como eu corrigir?

Att

**Comment by gustavowillam** [comment]
Olá Riviane!
Veja o exemplo abaixo. 
![image](https://user-images.githubusercontent.com/42176577/145442361-e6f34e22-614c-4166-93fb-971f4d4f95a2.png)

O eixo y está o valor observado (coluna Z.Obs.) enquanto que no eixo x está o valor predito (coluna Z.Predito).

Na pasta onde os arquivos do Smart-Map ficam salvos existe um arquivo .csv com os dados da validação cruzada. 
Geralmente o nome dele é: 1_Krig_#_CV.csv,  Onde o símbolo # é substituito pela variável que você está interpolando. 
Você pode abrir este arquivo no Excel e plotar um gráfico de dispersão entre as colunas (Z.Obs. e Z.Predito) para esclarecer melhor sua dúvida. 

Atenciosamente,
