### ISSUE TITLE
ValueError: range() arg 3 must not be zero 

### ISSUE THREAD

**Issue by mafelix13** [gustavowillam/SmartMapPlugin#16]
Traceback (most recent call last):
  File "C:\User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 1711, in pushButton_ImportQGIS_clicked

ymarks=[i for i in range(int(self.Cord_Y_min),int(self.Cord_Y_max,interval_y))]

ValueError: range() arg 3 must not be zero

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.22.1-Białowieża Białowieża, 663dcf8fb9

**Comment by jbellinzoni** [comment]
Hi @gustavowillam. I almost have the same problem.

ValueError: range() arg 3 must not be zero 
Traceback (most recent call last):
  File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 1711, in pushButton_ImportQGIS_clicked
    ymarks=[i for i in range(int(self.Cord_Y_min),int(self.Cord_Y_max) , interval_y)]
ValueError: range() arg 3 must not be zero

Versión de Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versión de QGIS: 3.10.11-A Coruña A Coruña, d2171173e4

**Comment by gustavowillam** [comment]
Hi @jbellinzoni , 
We have released a new version of smart map 1.1.1. In this version this error has been fixed. Remove version 1.1 and install this new version from the QGIS plugin repository.
Thanks for your contribution.
