### ISSUE TITLE
Can't find interpolated .kri files

### ISSUE THREAD

**Issue by geofausto** [gustavowillam/SmartMapPlugin#17]
For Management Zones creation I would like to add external variables but the option "Add External Values" does not find interpolated .kri files in my system. Not even those created by the plugin and saved in configured output folder.

![screenshot 2021-12-15 13-19-44](https://user-images.githubusercontent.com/7757383/146225968-e48a05cf-2d5f-4e66-afdd-3dda1b15685d.png)

Linux Mint 20.2 / Cinnamon 5.0.7 / Kernel 5.4.0-91-generic
QGIS 3.22.1-Białowieża

**Comment by gustavowillam** [comment]
Hi Fausto!

The .kri files are generated from the interpolation of attributes by the Kriging method available in the plugin. For each interpolated map, a file with a .kri extension is generated. They are usually stored in the Smart-Map folder generated by the plugin within your QGIS project folder.
An alternative is to change the extension of the maps files interpolated by Smart-Map, changing the .csv extension to .kri extension.
