### ISSUE TITLE
Interpolate over more than 1000 points

### ISSUE THREAD

**Issue by cnske** [gustavowillam/SmartMapPlugin#18]
This is more a feature request than an issues. 
It would be great if there will be an option which allows interpolation over more than 1000 points. Even though computation may take some time it would be worth it.

**Comment by gustavowillam** [comment]
Hi cnske!
Thanks for the contribution.
We are working on improvements to the plugin.
We intend to make available a new version where the user can configure the number of desired points.

**Comment by cnske** [comment]
Very happy to hear that @gustavowillam.
