### ISSUE TITLE
TypeError: sort_values() got an unexpected keyword argument 'ignore_index' 

### ISSUE THREAD

**Issue by julianoganzala** [gustavowillam/SmartMapPlugin#19]
Traceback (most recent call last):
  File "C:/Users/Juliano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 1748, in pushButton_ImportQGIS_clicked
    Semiv = semivariogram.Semivariogram(self.xy, self.z)
  File "C:/Users/Juliano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\krig\semivariogram.py", line 98, in __init__
    self.var=self.var.sort_values(by='lag',ignore_index=True) #o index não é atualizado
TypeError: sort_values() got an unexpected keyword argument 'ignore_index'

O que poderia estar ocorrendo e como consertar este problema?

**Comment by gustavowillam** [comment]
Na versão 1.1 do Smart-Map fizemos algumas correções de erros, e passamos a utilizar uma função do python (sort_values) que utiliza um parâmetro chamado: ignore_index.
Entretanto esse parâmetro só está disponivel para uma biblioteca python (pandas) a partir da versão 1.0.0 dessa biblioteca.
Logo, te sugiro atualizar para a ultima versão estável do QGIS 3.16.16 (https://qgis.org/downloads/QGIS-OSGeo4W-3.16.16-1-Setup-x86_64.exe) para corrigir esse problema de versão de biblioteca.
