### ISSUE TITLE
Erro ao processar

### ISSUE THREAD

**Issue by leofloresta** [gustavowillam/SmartMapPlugin#22]
Estou tendo o seguinte erro ao processar os dados:

OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647 
Traceback (most recent call last):
  File "C:\Users/leona/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 3453, in pushButton_VariogramaAjust_clicked
    self.calculate_variogram(initial_variogram = True, Nugget_Range_Sill = False)
  File "C:\Users/leona/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 3043, in calculate_variogram
    self.dlg.horizontalSlider_Nugget.setMaximum((self.gamma[len(self.gamma)-1])*1000)           #último valor de gamma (eixo y)
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647

Versão do Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versão do QGIS: 3.22.5-Białowieża Białowieża, c2723178

**Comment by gustavowillam** [comment]
Olá @leofloresta. 

Este erro está ocorrendo quando você está tentando ajustar o semivariograma para realizar a Krigagem, certo ? 

Quandos pontos você tem na camada de pontos ? 

Qual é o tamanho da área ?

**Comment by leofloresta** [comment]
Gustavo, bom dia!

Sim, o erro acontece no momento do ajuste

Tenho 5 pontos e a área é de 5483 km²

Obrigado

**Comment by gustavowillam** [comment]
@leofloresta , você tem uma área muito grande para poucos pontos. Logo o Smart Map não está conseguindo ajustar o semivariograma. 
Para estas situações, te aconselho utilizar a interpolação por Machine Learning. 
Veja este vídeo mostrando como utilizar Machine Learning no Smart Map. 
https://youtu.be/il2V6Y2IaIM?list=PLVmqNeV0L_zv2KgBiny2YmaGuIgarAMbN

Abraços,

**Comment by leofloresta** [comment]
Ontem fiz uma simulação criando 35 pontos aleatórios dentro dessa área e rodou perfeitamente.
Agora vou tentar por machine learning com os dados reais.
Grato pela atenção!!
