### ISSUE TITLE
Plugin SmartMap not showing in Menu and Toolbar

### ISSUE THREAD

**Issue by joaonaime** [gustavowillam/SmartMapPlugin#26]
I have successfully installed Smart Map plugin on QGIS 3.22.8-Biatowieza, Linux Mint 20.3 Cinnamon, Kernel 5.4.0-121. This plugin it is not found neither in the Menu nor in the Toolbar.

**Comment by gustavowillam** [comment]
Hi @joaonaime ,

If Smart-Map was successfully installed it should appear in the installed plugins interface.
However, it may be disabled, as shown in the figure above.
Click on the Smart-Map checkbox and see if it appears in the menu or toolbar.

![image](https://user-images.githubusercontent.com/42176577/177777594-5ce709f9-6668-4785-9e41-dfa5c2d0af5a.png)

**Comment by joaonaime** [comment]
Hi Gustavo. It was exactly what happened. The respective box was not
checked.
Thank you very much!

João Naime

Em qui., 7 de jul. de 2022 às 09:51, Gustavo Willam <
***@***.***> escreveu:
