### ISSUE TITLE
QGIS 3.22.11 LTR macOS 12.6 no TIFF file

### ISSUE THREAD

**Issue by mineraloge** [gustavowillam/SmartMapPlugin#27]
Hello,
I tried to work with your add-on on macOS 12.6 with the latest QGIS LTR version (3.22.11).
The version of Smart-Map is 1.2.
Everything works fine but at the end of the calculations I got a layer with an error that it couldn't find the TIFF file.
In the window of Smart-Map i could see the interpolated map but no TIFF was created in the output folder.
QGIS shows the following python warning:

`traceback: File "/Users/robertkoch/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/Smart_Map.py", line 672, in run               result = self.dlg.exec_() #button OK               File "/Users/robertkoch/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/Smart_Map.py", line 3809, in pushButton_Krigagem_clicked               Output_Layer_File_tiff = self.export_raster_to_qgis(Input_Table, Output_Layer_File_tiff, Output_Layer_Name, z_field)               File "/Users/robertkoch/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/Smart_Map.py", line 8322, in export_raster_to_qgis               CRS.createFromSrid(int(crs))` 

But no python error.

Thanks for your help.

Regards,
Robert

**Comment by gustavowillam** [comment]
Hello Robert, 

Update QGIS to the latest LTR version (3.28) and check if the error persists.
