### ISSUE TITLE
QGIS smart-map plugin - interpolation process stops at 85%

### ISSUE THREAD

**Issue by Janiveau** [gustavowillam/SmartMapPlugin#28]
Hello, after loading in the necessary data succesfully (including the calculation), the interpolation always stops at 85%, with different datasets as well. 
![smartmap](https://user-images.githubusercontent.com/115158817/194318044-1d5354be-abcc-4ba5-9245-874cc718729f.PNG).
Has someone an idea why this is going wrong? 

Regards,
Jan

**Comment by gustavowillam** [comment]
Hello,

How many points are you trying to interpolate?
