### ISSUE TITLE
Error while interpolation

### ISSUE THREAD

**Issue by ghost** [gustavowillam/SmartMapPlugin#30]
After calculating the variogram I press the interpolation buttom and when it´s 99% the following window appears
![Smart Map error](https://user-images.githubusercontent.com/115735243/195672332-bcbe3a8c-ed28-41d3-b53b-55d53808aca6.JPG)
Hope someone could help me

**Comment by gustavowillam** [comment]
This error was fixed in version 1.3 of the plugin already available in the qgis plugin repository.
Install the new version to fix the issue.
