### ISSUE TITLE
Plug in not working at all

### ISSUE THREAD

**Issue by juansecarvajalt** [gustavowillam/SmartMapPlugin#31]
Hey there,
I installed the smart map plug in on my QGis 3.26.3. When I try to select the data I'm going to use, the plug in freezes. It does not allow me to select the
![Capture](https://user-images.githubusercontent.com/116282987/196959359-15a3f2a8-5f5b-43b6-980b-d4a90e17f26c.PNG)
 boundaries, or other parameters, and the interpolate option can't be selected.

**Comment by ghost** [comment]
The plug in is having some problems with the latest version, try using Qgis 3.22

**Comment by gustavowillam** [comment]
Try installing the latest version of QGIS LTR (3.28) and check if the error is fixed.

**Comment by gustavowillam** [comment]
A new version of the plugin is available in the qgis repository.
Try installing this new version and update Qgis to version 3.28 LTR.
