### ISSUE TITLE
Key Error 3

### ISSUE THREAD

**Issue by boonits** [gustavowillam/SmartMapPlugin#32]
![image](https://user-images.githubusercontent.com/117131218/199137666-cc275c6b-6fcb-4f05-993c-9ec87001be0c.png)

Anyone know what's up with this error message? Occurs every time I try and import data

QGIS version 3.22.12

**Comment by gustavowillam** [comment]
Hello,

Error in python pandas library. Try installing the latest version of QGIS LTR (3.28) and check if the error is fixed.

**Comment by gustavowillam** [comment]
This error was fixed in version 1.3 of the plugin already available in the qgis plugin repository.
Install the new version to fix the issue and update Qgis to version 3.28 LTR.
