### ISSUE TITLE
Smart-map plugin. Can't choose the attribute

### ISSUE THREAD

**Issue by uzawadzka** [gustavowillam/SmartMapPlugin#33]
After an installation of plugin I could open it, but it sees only layer, and it couldn't find any field in Z list. I work on linux mint if it matters...
![smart-map-problem](https://user-images.githubusercontent.com/59049403/205268363-7669ff74-bb04-49c1-94f0-be6c8d8f562a.png)

**Comment by leonardo1404** [comment]
Hi! 
I'm experiencing the same issue using the LTR version of QGIS. When I open the plugin I receive this Python error:
![image](https://user-images.githubusercontent.com/64478837/205498179-ed10c8db-a219-416b-8b9c-b688a7d83d0d.png)
Also, when I try to change the selection of the input layer from the list I receive this other Python error:
![image](https://user-images.githubusercontent.com/64478837/205498235-95afb1bb-f119-406e-afdc-5a2760ae616e.png)

**Comment by JosimarGon** [comment]
### The same here.
System Pop_OS 22.04

An error has occurred while executing Python code: 

TypeError: setValue(self, int): argument 1 has unexpected type 'float' 
Traceback (most recent call last):
  File "/home/josimargon/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/Smart_Map.py", line 985, in mMapLayerComboBox_changed
    self.reset_gui()
  File "/home/josimargon/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/Smart_Map.py", line 735, in reset_gui
    self.dlg.horizontalSlider_Range.setValue(0.001)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'


Python version: 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0] 
QGIS version: 3.22.4-Białowieża Białowieża, exported

**Comment by uzawadzka** [comment]
I've bypassed it by using OSGeo4W on Windows, but I'm not happy with that as I have to use it on someone else's computer.

**Comment by nedhorning** [comment]
I'm using QGIS version: 3.28.3-Firenze on Ubuntu and have the same issue

**Comment by Nakakojinelson** [comment]
I am having the same problem. Have any of you found a solution to this problem?

**Comment by gustavowillam** [comment]
This error was fixed in version 1.3 of the plugin already available in the qgis plugin repository.
Install the new version to fix the issue and update Qgis to version 3.28 LTR.
