### ISSUE TITLE
TypeError: disconnect() failed between 'currentIndexChanged' and all its connections 

### ISSUE THREAD

**Issue by NotAnEmu95** [gustavowillam/SmartMapPlugin#35]
G'day,

I am trying to interpolate between some points, but am getting the following error:

`TypeError: disconnect() failed between 'currentIndexChanged' and all its connections 
Traceback (most recent call last):
  File "C:\Users/Pat/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 3807, in pushButton_Krigagem_clicked
    self.dlg.mMapLayerComboBox.currentIndexChanged.disconnect()
TypeError: disconnect() failed between 'currentIndexChanged' and all its connections

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.3-Firenze Firenze, c12bcb2f76c 

Python Path:
C:/PROGRA~1/QGIS32~1.2/apps/qgis/./python
C:/Users/Pat/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Pat/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.2/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.28.2\bin\python39.zip
C:\PROGRA~1\QGIS32~1.2\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib
C:\Program Files\QGIS 3.28.2\bin
C:\PROGRA~1\QGIS32~1.2\apps\Python39
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Pat/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users/Pat/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\Pat\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:/Users/Pat/Desktop/PhD/Training QGIS`

Any help would be appreciated.

All the best!

**Comment by catharsis79** [comment]
same issue here on the same QGIS version (Firenze)

**Comment by gustavowillam** [comment]
Hello,

This error: self.dlg.mMapLayerComboBox.currentIndexChanged.disconnect()

occurred when trying to export the raster file to qgis.

This error is related to the selection box (where you select the input layer in the data tab) of the graphical interface. Checkbox disconnected from python code.

Solution: Close the application and open it again. Select the input layer, select the attribute to be interpolated. On the grid tab, define the size of the pixel and the polygon around the area (if any), then go to the kriging interpolation tab, adjust the semivariogram and perform the kriging interpolation.

**Comment by gustavowillam** [comment]
This error was fixed in version 1.3 of the plugin already available in the qgis plugin repository.
Install the new version to fix the issue and update Qgis to version 3.28 LTR.
