### ISSUE TITLE
Problem on Mac OSX

### ISSUE THREAD

**Issue by asolis08219** [gustavowillam/SmartMapPlugin#4]
Tengo un inconveniente al tratar de usar el complemento en una Mac, gracias por el apoyo: 

Ha ocurrido un error mientras se ejecutaba el código de Python: 

UnicodeEncodeError: 'ascii' codec can't encode characters in position 15-16: ordinal not in range(128) 
Traceback (most recent call last):
  File "/Users/ingabel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/Smart_Map.py", line 1640, in pushButton_ImportQGIS_clicked
    Semiv = semivariogram.Semivariogram(self.xy, self.z)
  File "/Users/ingabel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/krig/semivariogram.py", line 69, in __init__
    Log('\nIniciando Geração do Semivariograma\n')
  File "/Users/ingabel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/krig/semivariogram.py", line 40, in Log
    f.write(msg+'\n')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 15-16: ordinal not in range(128)

Versión de Python: 3.8.7 (default, Feb 10 2021, 09:04:08) [Clang 12.0.0 (clang-1200.0.32.29)] 
Versión de QGIS: 3.18.2-Zürich Zürich, 44d7dfabbe 

Ruta de Python:
/Users/ingabel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/planet_explorer/extlibs
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/ingabel/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/ingabel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/snuggs-1.4.7-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/opencv_contrib_python-4.3.0.36-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/pyproj-2.6.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/statsmodels-0.11.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/click_plugins-1.1.1-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/scipy-1.5.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/geopandas-0.8.1-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/affine-2.3.0-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages
/Applications/QGIS.app/Contents/MacOS/lib/python38.zip
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/patsy-0.5.1-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/GDAL-3.2.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/rasterio-1.1.5-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/numpy-1.20.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/lib-dynload
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/pandas-1.1.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/Rtree-0.9.4-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/cftime-1.2.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/Fiona-1.8.13.post1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/netCDF4-1.5.4-py3.8-macosx-10.13.0-x86_64.egg
/Users/ingabel/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/ingabel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DigitizingTools/tools
/Users/ingabel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DigitizingTools
/Users/ingabel/Documents/SIG Proyectos/CU RIEGOS SIG

**Comment by gustavowillam** [comment]
Hi!
I have released an update which can be found in the QGIS repository (https://plugins.qgis.org/plugins/Smart_Map/) or on GitHub (https://github.com/gustavowillam/SmartMapPlugin/releases/download/v1. 1/Smart_Map.zip) for plugin version 1.1 to fix the problem.
I hope this update can resolve the issue.
Thank you!
