### ISSUE TITLE
Intrpolation dosen't work 

### ISSUE THREAD

**Issue by BASSANOUREDINE** [gustavowillam/SmartMapPlugin#40]
hello everyone,
I wonder if anyone could help me with the this issue,
 I have QGIS 3.28 and python3 installed. I have no problem at first, but when I run the interpolation QGIS crashes.

Best regards.

**Comment by gustavowillam** [comment]
A new version of the plugin is available in the qgis repository.
Try installing this new version and update Qgis to version 3.28 LTR.

**Comment by BASSANOUREDINE** [comment]
Thanks a lot
