### ISSUE TITLE
TypeError: disconnect() failed between 'currentIndexChanged' and all its connections

### ISSUE THREAD

**Issue by iliasmachairas** [gustavowillam/SmartMapPlugin#41]
I encountered the following error when I pressed interpolate button. The previous steps executed successfully. 

Traceback (most recent call last):
  File "C:\Users/i_macheras/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 3810, in pushButton_Krigagem_clicked
    self.dlg.mMapLayerComboBox.currentIndexChanged.disconnect()
TypeError: disconnect() failed between 'currentIndexChanged' and all its connections

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.30.0-'s-Hertogenbosch 's-Hertogenbosch, f186b8efe0e

**Comment by Ovenil** [comment]
Same error

**Comment by gustavowillam** [comment]
Your installed QGIS version is 3.30. The latest stable (LTR) version of QGIS is 3.28. Smart-Map is updated and tested in LTR versions of QGIS. So I suggest you uninstall the latest version of QGIS (3.30) and install the latest stable version of QGIS 3.28.
