### ISSUE TITLE
module 'numpy' has no attribute 'float'

### ISSUE THREAD

**Issue by ThomasStruller** [gustavowillam/SmartMapPlugin#42]
on clicking import I got these message:

AttributeError: module 'numpy' has no attribute 'float' 
Traceback (most recent call last):
  File "C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 1704, in pushButton_ImportQGIS_clicked
    self.data = np.array( self.data, dtype=np.float )
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'

Python-Version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS-Version: 3.30.2-'s-Hertogenbosch 's-Hertogenbosch, 0992b533 

Python-Pfad:
C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pdaltools
C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\contour
C:/OSGeo4W/apps/qgis/./python
C:/Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis/./python/plugins
C:\OSGeo4W\apps\grass\grass82\etc\python
C:\OSGeo4W\bin
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages\win32
C:\OSGeo4W\apps\Python39\lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin
C:/Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing
C:\Users\thomas.struller\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing
C:\Users\thomas.struller\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs
C:\Users\thomas.struller\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages
W:/Nuernberg_Sandreuth/2023118

**Comment by gustavowillam** [comment]
Your installed QGIS version is 3.30. The latest stable (LTR) version of QGIS is 3.28. Smart-Map is updated and tested in LTR versions of QGIS. So I suggest you uninstall the latest version of QGIS (3.30) and install the latest stable version of QGIS 3.28.

**Comment by colemanjj** [comment]
I installed QGIS 3.28 as you suggested and still get the error that 'numpy' has no attribute 'float' see below:

An error has occurred while executing Python code: 
AttributeError: module 'numpy' has no attribute 'float' 
Traceback (most recent call last):
  File "C:\Users/john/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 1632, in pushButton_ImportQGIS_clicked
    self.data_outlier = np.array( self.data_outlier, dtype=np.float )
  File "C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.6-Firenze Firenze, 868c9fa03b

**Comment by gustavowillam** [comment]
The new Smart-Map version 1.3.2 that fixes the above bug is available for installation from the QGIS plugin repository.

**Comment by colemanjj** [comment]
Thank you. Your smart-map plugin is very impressive!
john


     On Tuesday, May 16, 2023, 07:37:05 AM GMT-5, Gustavo Willam ***@***.***> wrote:  
 
 


The new Smart-Map version 1.3.2 that fixes the above bug is available for installation from the QGIS plugin repository.
