### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'ccw' 

### ISSUE THREAD

**Issue by Ovenil** [gustavowillam/SmartMapPlugin#43]
Um erro ocorreu enquanto executava o código Python: 

ValueError: invalid literal for int() with base 10: 'ccw' 
Traceback (most recent call last):
  File "C:\Users/Ricardo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 3812, in pushButton_Krigagem_clicked
    Output_Layer_File_tiff = self.export_raster_to_qgis(Input_Table, Output_Layer_File_tiff, Output_Layer_Name, z_field)
  File "C:\Users/Ricardo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 8432, in export_raster_to_qgis
    self.define_raster_color_ramp(rlayer, Output_Layer_Name)
  File "C:\Users/Ricardo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 8558, in define_raster_color_ramp
    QgsColorRampShader.ColorRampItem(classes[2], QColor(int(stops[6]),int(stops[7]),int(stops[8]),int(stops[9])), '%.6f' % classes[2]),
ValueError: invalid literal for int() with base 10: 'ccw'

Versão do Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versão do QGIS: 3.30.2-'s-Hertogenbosch 's-Hertogenbosch, 0992b533 

Caminho do Python:
D:/QGIS/apps/qgis/./python
C:/Users/Ricardo/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Ricardo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
D:/QGIS/apps/qgis/./python/plugins
D:\QGIS\apps\grass\grass82\etc\python
C:\Users\Ricardo\Documents
D:\QGIS\bin\python39.zip
D:\QGIS\apps\Python39\DLLs
D:\QGIS\apps\Python39\lib
D:\QGIS\bin
D:\QGIS\apps\Python39
D:\QGIS\apps\Python39\lib\site-packages
D:\QGIS\apps\Python39\lib\site-packages\win32
D:\QGIS\apps\Python39\lib\site-packages\win32\lib
D:\QGIS\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Ricardo/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Ricardo/Desktop/Semestre 22-2/TCC2/QGIS/TCC_AP

**Comment by gustavowillam** [comment]
Your installed QGIS version is 3.30. The latest stable (LTR) version of QGIS is 3.28. Smart-Map is updated and tested in LTR versions of QGIS. So I suggest you uninstall the latest version of QGIS (3.30) and install the latest stable version of QGIS 3.28.
