### ISSUE TITLE
The np.float and np.int attributes have become obsolete in the new numpy of QGIS.

### ISSUE THREAD

**Issue by alepr** [gustavowillam/SmartMapPlugin#44]

**Comment by colemanjj** [comment]
it looks like the QGIS version of  python (3.9.5) uses a recent version of numpy which does not recognize "float" . Can the code in SmartMap be updated to resolve this problem?  I have downgraded to QGIS 3.28 and it still uses python 3.9.5  > I'd love to use this plugin but...

**Comment by alepr** [comment]
I solved the problem changing np.float by only float (without quotes) in the Smart_map.py file in the QGIS plugin directory. It's a temporary fix until the update

**Comment by colemanjj** [comment]
Great. I'll try that. I also got it to work by rolling back to QGIS 3.22 which must use an earlier version of numpy

**Comment by gustavowillam** [comment]
The new Smart-Map version 1.3.2 that fixes the above bug is available for installation from the QGIS plugin repository.
