### ISSUE TITLE
Click on interpolate and nothing happens

### ISSUE THREAD

**Issue by ahinoamp** [gustavowillam/SmartMapPlugin#45]
Hi,

I don't know if anyone encountered this issue - but I click on interpolate and I get a progress bar.
For a very small grid, after 5 minutes - the progress bar hasn't moved and I'm not sure anything is actually running in the backend.

Any tip?

Thanks!

**Comment by gustavowillam** [comment]
Hello, Ahinoam Pollack!

Does an error appear?
How many points are you trying to interpolate?
If an error occurs, give me more details of the error.
If possible copy and paste here the python error that appears during interpolation by Kriging.

Thanks!
