### ISSUE TITLE
The interpolation tool is not working

### ISSUE THREAD

**Issue by reghais** [gustavowillam/SmartMapPlugin#48]
Thanks to the developers of this great add-on

I would like to tell about a problem 
Although I installed the add-on well and it is now working fine in both "Data" and "Grid" phases. However, when performing interpolation, it does not work, especially in the Krigin method, and yet it takes a long time in a machine learning method (My data consists of 17 sites).

Please help me solve this problem

**Comment by gustavowillam** [comment]
Hello Reghais Azzeddine! 

What error appears?
Give me more details of the error. 
If possible copy and paste here the python error that appears during interpolation by Kriging.

**Comment by reghais** [comment]
Hi dear gustaviwillam

I have re-installed the plugin and it works fine now Thanks for your reply and for wanting to help me My heartfelt greetings to you
