### ISSUE TITLE
TypeError: disconnect() failed between 'currentIndexChanged' and all its connections

### ISSUE THREAD

**Issue by pcBJ** [gustavowillam/SmartMapPlugin#51]
Um erro ocorreu enquanto executava o código Python: 

TypeError: disconnect() failed between 'currentIndexChanged' and all its connections 
Traceback (most recent call last):
  File "C:\Users/z/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 3810, in pushButton_Krigagem_clicked
    self.dlg.mMapLayerComboBox.currentIndexChanged.disconnect()
TypeError: disconnect() failed between 'currentIndexChanged' and all its connections

Versão do Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versão do QGIS: 3.30.0-'s-Hertogenbosch 's-Hertogenbosch, f186b8efe0e

**Comment by gusluz** [comment]
Mesmo erro aqui!
Cheguei a realizar uma krigagem, foi gerado o mapa, tudo certo.
No entanto, após tentar novamente foi retornado este erro.
No seu caso eu recomento testar na versão LTR do QGIS:
https://ftp.osuosl.org/pub/osgeo/download/qgis/windows/QGIS-OSGeo4W-3.28.10-1.msi?US

**Comment by pcBJ** [comment]
Mesmo atualizando o qgis tanto para a versão 3.30 o erro continua o mesmo.

**Comment by gustavowillam** [comment]
Uma nova versão do Smart-Map está disponível no repositório do QGIS. Instale a nova versão (1.4) juntamente com a ultima versão estável do QGIS (3.34 LTR).
