### ISSUE TITLE
2023-08-25T19:31:19     WARNING    Error de Python : Ha ocurrido un error mientras se ejecutaba el código de Python: Vea el registro de mensajes (Error de Python) para más detalles.

### ISSUE THREAD

**Issue by MarianaRodriguez8888** [gustavowillam/SmartMapPlugin#53]
HELLO lately you can't use the application because I get an error reading the python code. I hope you can help me

2023-08-25T19:31:19     WARNING    Traceback (most recent call last):
              File "C:\Users/Equipo/AppData/Roaming/QGIS/QGIS3\profiles\Mariana/python/plugins\SmartMapPlugin-master\Smart_Map.py", line 383, in run
              isrunning = plugins["Smart_Map"]
             KeyError: 'Smart_Map'
            
![image](https://github.com/gustavowillam/SmartMapPlugin/assets/143229083/fa9cc43c-def8-4078-b9b6-f8f8f0d54101)

Ha ocurrido un error mientras se ejecutaba el código de Python: 

KeyError: 'Smart_Map' 
Traceback (most recent call last):
  File "C:\Users/Equipo/AppData/Roaming/QGIS/QGIS3\profiles\Mariana/python/plugins\SmartMapPlugin-master\Smart_Map.py", line 383, in run
    isrunning = plugins["Smart_Map"]
KeyError: 'Smart_Map'

Versión de Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versión de QGIS: 3.28.9-Firenze Firenze, 66f4d63ad4 

Ruta de Python:
C:/PROGRA~1/QGIS32~1.9/apps/qgis-ltr/./python
C:/Users/Equipo/AppData/Roaming/QGIS/QGIS3\profiles\Mariana/python
C:/Users/Equipo/AppData/Roaming/QGIS/QGIS3\profiles\Mariana/python/plugins
C:/PROGRA~1/QGIS32~1.9/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS32~1.9\apps\grass\grass83\etc\python
C:\Users\Equipo\Documents
C:\Program Files\QGIS 3.28.9\bin\python39.zip
C:\PROGRA~1\QGIS32~1.9\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.9\apps\Python39\lib
C:\Program Files\QGIS 3.28.9\bin
C:\PROGRA~1\QGIS32~1.9\apps\Python39
C:\PROGRA~1\QGIS32~1.9\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.9\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.9\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.9\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Equipo/AppData/Roaming/QGIS/QGIS3\profiles\Mariana/python
C:\Users/Equipo/AppData/Roaming/QGIS/QGIS3\profiles\Mariana/python/plugins\SwapVectorDirection
C:/Users/Equipo/Desktop/Maiz lote 10

**Comment by gustavowillam** [comment]
A new version of Smart-Map is available in the QGIS repository. Install the new version (1.4) together with the latest stable version of QGIS (3.34 LTR).
