### ISSUE TITLE
TypeError: disconnect() failed between 'currentIndexChanged' and all its connections 

### ISSUE THREAD

**Issue by gusluz** [gustavowillam/SmartMapPlugin#54]
Um erro ocorreu enquanto executava o código Python: 

TypeError: disconnect() failed between 'currentIndexChanged' and all its connections 
Traceback (most recent call last):
  File "C:\Users/GUSTAVO/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 3810, in pushButton_Krigagem_clicked
    self.dlg.mMapLayerComboBox.currentIndexChanged.disconnect()
TypeError: disconnect() failed between 'currentIndexChanged' and all its connections

Versão do Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versão do QGIS: 3.28.10-Firenze Firenze, e2edb9c468 

Caminho do Python:
C:/PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python
C:/Users/GUSTAVO/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/GUSTAVO/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS32~1.10\apps\grass\grass83\etc\python
C:\Users\GUSTAVO\Documents
C:\Program Files\QGIS 3.28.10\bin\python39.zip
C:\PROGRA~1\QGIS32~1.10\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.10\apps\Python39\lib
C:\Program Files\QGIS 3.28.10\bin
C:\PROGRA~1\QGIS32~1.10\apps\Python39
C:\PROGRA~1\QGIS32~1.10\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.10\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.10\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.10\apps\Python39\lib\site-packages\Pythonwin
C:/Users/GUSTAVO/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\GUSTAVO\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages
C:/Users/GUSTAVO/Documents/original analys_shp

**Comment by gustavowillam** [comment]
Uma nova versão do Smart-Map está disponível no repositório do QGIS. Instale a nova versão (1.4) juntamente com a ultima versão estável do QGIS (3.34 LTR).
