### ISSUE TITLE
pop up window displays with everything overlapping 

### ISSUE THREAD

**Issue by ivanaivanaivana** [gustavowillam/SmartMapPlugin#55]
Hello everyone! I reach out to you regarding a problem using the QGIS plugin called SMART MAP. In order to better understand the problem I added a screenshot. As you can see I does not allow me to maximize the tab, making it impossible to work on since all the parameters overlap with each other.
QGIS version 3.28, PLUGIN (smart map) version 1.3.3
Things I already tried:
downloading version 1.3.2 and 1.3.1 of smart map
downloading version 3.24 of QGIS and installing the versions 1.3.3, 1.3.2 and 1.3.1.
making sure versions are compatible
If anyone has had this problem or has an idea on how to fix it, I would really appreciate it. Thanks! 

![image](https://github.com/gustavowillam/SmartMapPlugin/assets/143020322/d6b2609e-a586-4d98-b634-1f66cd9c86b1)

**Comment by gustavowillam** [comment]
A new version of Smart-Map is available in the QGIS repository. Install the new version (1.4) together with the latest stable version of QGIS (3.34 LTR).
