### ISSUE TITLE
Interpolação via script

### ISSUE THREAD

**Issue by cbeloni** [gustavowillam/SmartMapPlugin#57]
Boa tarde ! 
Parabéns pelo ótimo trabalho! 
Temos alguma forma de executar o plugin fora do QGIS? Fiz alguns testes e o resultado do plugin é exatamente o que preciso, mas preciso colocar em uma aplicação onde o usuário irá gerar dinamicamente os mapas por uma interface web (fora do QGIS). 

Obrigado!

**Comment by sarviovalente** [comment]
Prezado Cauê,

Possível sim, toma um tempo para adequação.

Abraço
Sarvio

Em dom., 17 de set. de 2023 às 19:15, Cauê Beloni ***@***.***>
escreveu:
