### ISSUE TITLE
Issue with smart-map plugin  (Um erro ocorreu enquanto executava o código Python: )

### ISSUE THREAD

**Issue by data-soil** [gustavowillam/SmartMapPlugin#58]
The same issue is happening in QGIS 3.10 and 3.16

Um erro ocorreu enquanto executava o código Python: 

TypeError: sort_values() got an unexpected keyword argument 'ignore_index' 
Traceback (most recent call last):
  File "C:/Users/michael.goulart/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 1814, in pushButton_ImportQGIS_clicked
    Semiv = semivariogram.Semivariogram(self.xy, self.z)
  File "C:/Users/michael.goulart/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\krig\semivariogram.py", line 98, in __init__
    self.var=self.var.sort_values(by='lag',ignore_index=True) #o index não é atualizado
TypeError: sort_values() got an unexpected keyword argument 'ignore_index'

Versão do Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versão do QGIS: 3.10.0-A CoruÃ±a A CoruÃ±a, 6c816b4204 

Caminho do Python:
C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python
C:/Users/michael.goulart/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/michael.goulart/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.10\bin\python37.zip
C:\PROGRA~1\QGIS3~1.10\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib
C:\Program Files\QGIS 3.10\bin
C:\Users\michael.goulart\AppData\Roaming\Python\Python37\site-packages
C:\PROGRA~1\QGIS3~1.10\apps\Python37
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\Pythonwin
C:/Users/michael.goulart/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\michael.goulart\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages
C:/Users/michael.goulart/Desktop/DADOS_EVOLUÇÃO

**Comment by data-soil** [comment]
![ERRO](https://github.com/gustavowillam/SmartMapPlugin/assets/145713275/07592f8c-1816-418c-b6de-7f5b7b04ee28)

**Comment by data-soil** [comment]
If I use the QGIS 3.32 version: 

An error has occurred while executing Python code: 

AttributeError: module 'numpy' has no attribute 'float' 
Traceback (most recent call last):
  File "C:\Users/michael.goulart/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 1690, in pushButton_ImportQGIS_clicked
    self.data_outlier = np.array( self.data_outlier, dtype=np.float )
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.32.3-Lima Lima, 67d46100b5 

Python Path:
C:/PROGRA~1/QGIS33~1.3/apps/qgis/./python
C:/Users/michael.goulart/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/michael.goulart/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.3/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~1.3\apps\grass\grass83\etc\python
C:\Users\michael.goulart\Documents
C:\Program Files\QGIS 3.32.3\bin\python39.zip
C:\PROGRA~1\QGIS33~1.3\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib
C:\Program Files\QGIS 3.32.3\bin
C:\Users\michael.goulart\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS33~1.3\apps\Python39
C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/michael.goulart/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/michael.goulart/Dropbox/Data Soil Int. Agr/FAZ. GUARA - EDUARDO ZANELLA/2023/DADOS_EVOLUÇÃO

**Comment by gustavowillam** [comment]
A new version of Smart-Map is available in the QGIS repository. Install the new version (1.4) together with the latest stable version of QGIS (3.34 LTR).
