### ISSUE TITLE
Demora na geração de KO e ML

### ISSUE THREAD

**Issue by gustavoarrial** [gustavowillam/SmartMapPlugin#60]
Olá galera, tudo bem?

Há um tempo tenho tentado fazer KO's, até consigo, mas demora mais de hora. 
Teria duas questões:  Pode ser a versão o do software do Qgis? Pode ser poque tenho poucos pontos plotados?

Atenciosamente

**Comment by sarviovalente** [comment]
Gustavo,

Você poderia ter passado pra gente as informações. Quantos hectares é a
área que está fazendo a interpolação? Qual tamanho dos pixels?...

Abraço

Em qua., 29 de nov. de 2023 às 14:57, gustavoarrial <
***@***.***> escreveu:

**Comment by gustavowillam** [comment]
Uma nova versão do Smart-Map está disponível no repositório do QGIS. Instale a nova versão (1.4) juntamente com a ultima versão estável do QGIS (3.34 LTR).

**Comment by gustavoarrial** [comment]
Olá galera, desculpe a demora, mas o problema não era o Qgis e tampouco o Smart-Map. 

Meus dados não serviam para esssa abordagem metodológica, em todo caso, obrigado pelo suporte. 

Abraço
