### ISSUE TITLE
About installation of the Smart-Map plugin.

### ISSUE THREAD

**Issue by reghais** [gustavowillam/SmartMapPlugin#61]
Dear author

I tried different versions of QGIS and Python, but I was unable to successfully install the Smart-Map plugin.
Which versions of QGIS and Python do you recommend and think are better for installing the Smart-Map plugin?

**Comment by gustavowillam** [comment]
Hi,

Use the latest LTR (Long Term Release) version of QGIS, 3.28 (https://qgis.org/downloads/QGIS-OSGeo4W-3.28.13-2.msi) with version 1.3.3 of SmartMap (https://plugins.qgis.org /plugins/Smart_Map/version/1.3.3/).

**Comment by reghais** [comment]
Many thanks Pr. @gustavowillam 
I have already tried both of these versions and now the Smart-Map plugin  one works fine.

Best regards

**Comment by reghais** [comment]
Thank you @gustavowillam once again for the tutorial. I found it to be informative and straightforward. However, I would appreciate some assistance with figures 6 and 7 in your paper. Could you guide me on how to create these?

**Comment by gustavowillam** [comment]
Hi @reghais . 

In Figure 6, the bivariate Moran Index is displayed between the attributes P, K, Ca, Mg (y axis) and the other attributes (x axis). To find the bivariate Moran Index I used the python pysal library (https://pysal.org/) through a python script that I implemented.
With the data obtained, I saved it in a .csv file. From the .csv file, I generated the graph using the ggplot library in the R language.

To obtain R2 in Figure 7 I used Smart-Map. In the SVM2 method, I added the covariates (features) with the highest correlation found in figure 6. I used the R2 of cross-validation.
Again, I saved the data in a .csv file and generated the graph using the ggplot library in the R language.

**Comment by reghais** [comment]
Thank you, professor @gustavowillam , for your invaluable explanation.
I have obtained the univariate and bivariate Moran results using the Support Vector Machine (SVM) button within the Smart-Map plugin.
Thus, in light of your response, So I still think  that i am correct and I don't need to run it in Python

Regards

**Comment by gustavowillam** [comment]
Yes, it is possible to view the bivariate Moran Index in SVM interpolation in the "Selection of Variables" tab. The python script that I ran had the objective of automating the process and generating the .csv file that was used as input for the script made in R using the ggplot library to generate the graph. The issue is that the plugin does not generate the graphs in figures 6 and 7. It was necessary to implement a script to create the graphs.

Best regards,

**Comment by reghais** [comment]
The discussion with you proved highly beneficial, Professor @gustavowillam 
It is my sincere wish that the individuals utilizing this add-on will discover our discourse to be advantageous and a solution to their problems
Thank you again for this good plugin
I eagerly anticipate your future contributions, where you may further enhance the QGIS by introducing additional techniques and approaches for map interpolation, such as the Empirical Bayesian Kriging Interpolation Method.
I also look forward to inviting you to participate in my future papers. I truly hope so.

Best regards

**Comment by gustavowillam** [comment]
Thanks @reghais !

There are other Kriging methods that can be implemented as well as Machine Learning methods.
We will work to make these methods available in the plugin.

Best Regards,
