### ISSUE TITLE
ZeroDivisionError: float division by zero 

### ISSUE THREAD

**Issue by catherinebernal** [gustavowillam/SmartMapPlugin#66]
buena dia, he corrido en repetidas ocasiones el ejercicio ya para poder obtener las zonas de manejo y en el momento de generar me sale el siguiente error, estoy tratando de combinar dos variables a las cuales ya les realice la operacion krigking (Cea y elevacion): 

**ZeroDivisionError: float division by zero** 
Traceback (most recent call last):
  File "C:\Users/Geo_2024/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 8141, in pushButton_ZM_Calcular_clicked
    Output_Layer_File_tiff = self.export_raster_to_qgis(Input_Table, Output_Layer_File_tiff, Output_Layer_Name, z_field)
  File "C:\Users/Geo_2024/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 8271, in export_raster_to_qgis
    self.Num_Points_X = int((float(self.Cord_X_max) - float(self.Cord_X_min)) / float(self.Pixel_Size_X_ZM))
ZeroDivisionError: float division by zero

Versión de Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versión de QGIS: 3.28.7-Firenze Firenze, fedae0eb52 

Ruta de Python:
C:/PROGRA~1/QGIS32~1.7/apps/qgis-ltr/./python
C:/Users/Geo_2024/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Geo_2024/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.7/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS32~1.7\apps\grass\grass82\etc\python
C:\Users\Geo_2024\Documents
C:\Program Files\QGIS 3.28.7\bin\python39.zip
C:\PROGRA~1\QGIS32~1.7\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.7\apps\Python39\lib
C:\Program Files\QGIS 3.28.7\bin
C:\Users\Geo_2024\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS32~1.7\apps\Python39
C:\PROGRA~1\QGIS32~1.7\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.7\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.7\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.7\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Geo_2024/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users/Geo_2024/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geosys-plugin
C:\Users\Geo_2024\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:\Users\Geo_2024\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qfieldsync\libqfieldsync.whl
C:\Users\Geo_2024\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages
C:\PROGRA~1\QGIS3~1.4\apps\qgis-ltr\python
I:/KTE

**Comment by gustavowillam** [comment]
A new version of Smart-Map is available in the QGIS repository. Install the new version (1.4) together with the latest stable version of QGIS (3.34 LTR).
