### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'rgb:0.84313725490196079'

### ISSUE THREAD

**Issue by lucasrottasimon** [gustavowillam/SmartMapPlugin#67]
Olá, Gustavo.
Estou tentando processar uma interpolação e tem ocorrido o seguinte erro:

An error has occurred while executing Python code: 

ValueError: invalid literal for int() with base 10: 'rgb:0.84313725490196079'
Traceback (most recent call last):
  File "C:\Users/itcd2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 3812, in pushButton_Krigagem_clicked
    Output_Layer_File_tiff = self.export_raster_to_qgis(Input_Table, Output_Layer_File_tiff, Output_Layer_Name, z_field)
  File "C:\Users/itcd2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 8432, in export_raster_to_qgis
    self.define_raster_color_ramp(rlayer, Output_Layer_Name)
  File "C:\Users/itcd2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 8503, in define_raster_color_ramp
    c1 = [ int(element) for element in rp['color1'].split(',') ]           #first color  Ex: red
  File "C:\Users/itcd2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 8503, in 
    c1 = [ int(element) for element in rp['color1'].split(',') ]           #first color  Ex: red
ValueError: invalid literal for int() with base 10: 'rgb:0.84313725490196079'
 

Python version: 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)] 
QGIS version: 3.36.0-Maidenhead Maidenhead, 09951dc0 

Python Path:
C:\Users/itcd2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoINCRA
C:/PROGRA~1/QGIS33~1.0/apps/qgis/./python
C:/Users/itcd2/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/itcd2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~1.0\apps\grass\grass83\etc\python
D:\PVs_Urbanas\Caxias do Sul\PV_Caxias_do_Sul_Rev_06
C:\PROGRA~1\QGIS33~1.0\bin\python39.zip
C:\PROGRA~1\QGIS33~1.0\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib
C:\PROGRA~1\QGIS33~1.0\bin
C:\PROGRA~1\QGIS33~1.0\apps\Python39
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\Pythonwin
C:/Users/itcd2/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\itcd2\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages
D:/PVs_Urbanas/Caxias do Sul/PV_Caxias_do_Sul_Rev_06

Você consegue me ajudar?
Obrigado.

**Comment by gustavowillam** [comment]
Olá Lucas!

Uma nova versão do Smart-Map está disponível no repositório do QGIS. Instale a nova versão (1.4) juntamente com a ultima versão estável do QGIS (3.34 LTR).

**Comment by lucasrottasimon** [comment]
Olá, Gustavo.
Obrigado, vou testar.
