### ISSUE TITLE
Interpolação com dados zerados

### ISSUE THREAD

**Issue by ClauLud** [gustavowillam/SmartMapPlugin#70]
Estou tentando fazer interpolação, mas o mapa gerado no Complemento é diferente do que é salvo no Qgiz, ele chega com valores zerados.
Já diminui o caminho do arquivo, não há espaços ou caracteres especiais.
Já tentei alternar a estilização de camada para banda simples cinza e banda simples falsa cor.
Já tentei puxar a camada gerada direto da pasta para o projeto, mas além de vir igual, ainda aparece um erro (ao lado do nome).
As camadas estão em UTM SIRGAS 22S, fiz por reprojeção. O projeto TB está em no mesmo sistema. 

Vou encaminhar alguns prints, caso alguém possa me ajudar ficaria extremamente grata.

![Captura de tela 2024-04-24 161850](https://github.com/gustavowillam/SmartMapPlugin/assets/167799677/90da5064-059e-43cc-85e1-3c3a937c9a5a)
![Captura de tela 2024-04-29 135808](https://github.com/gustavowillam/SmartMapPlugin/assets/167799677/76f83e08-f619-43e2-8d37-764f0fb79379)
![Captura de tela 2024-04-29 135844](https://github.com/gustavowillam/SmartMapPlugin/assets/167799677/129ec799-e8cf-42ac-8147-b48fce221416)
![Captura de tela 2024-04-29 135932](https://github.com/gustavowillam/SmartMapPlugin/assets/167799677/c4894349-5d19-4625-b5cb-129bcac81357)

**Comment by ClauLud** [comment]
Ninguém que possa me ajudar?

**Comment by sarviovalente** [comment]
Ola, acho que você precisa tomar um pouco mais de cuidado como utiliza os
dados no SM. Veja como está a sua coluna

[image: image.png]


Você poderia salvar esses dados como um Arquivo CSV (exportar). Depois
importar novamente o CSV, preparar melhor esses dados, com um nome na
coluna. E depois dos pontos com a tabela de atributo consistente, você
tentar utilizar o SM?

Att
Sárvio Valente

Em ter., 7 de mai. de 2024 às 16:06, ClauLud ***@***.***>
escreveu:
