### ISSUE TITLE
Plugin installation error

### ISSUE THREAD

**Issue by nuhanb** [gustavowillam/SmartMapPlugin#72]
I am not able to install the plugin after I update to latest QGIS 3.34.6-Prizren. Previously I have used the plugin and it worked fine when using QGIS 3.2.
I am not a programmer and don't really know how to troubleshoot if the problem relates to python or other programming language etc.. if anyone can kindly guide me step by step, I'd be grateful. I have also tried to solve the scikit error & pip installation guided by youtube tutorials and forums, but to no avail. Maybe there's something or some steps I'm missing somewhere I am not sure. Error as shown below:

Couldn't load plugin 'Smart_Map' due to an error when calling its classFactory() method 

ImportError: No module named 'sklearn.__check_build._check_build' ___________________________________________________________________________ Contents of C:\Users\hanisah\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages\sklearn\__check_build: setup.py                  _check_build.cp37-win_amd64.pyd_check_build.cp39-win_amd64.pyd __init__.py              __pycache__ ___________________________________________________________________________ It seems that scikit-learn has not been built correctly. If you have installed scikit-learn from source, please do not forget to build the package before using it: run `python setup.py install` or `make` in the source directory. If you have used an installer, please check that it is suited for your Python version, your operating system and your platform. 
Traceback (most recent call last):
  File "C:\Users\hanisah\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages\sklearn\__check_build\__init__.py", line 44, in 
    from ._check_build import check_build  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1/QGIS33~1.6/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'sklearn.__check_build._check_build'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.6/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/hanisah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\__init__.py", line 36, in classFactory
    from .Smart_Map import smart_map
  File "C:\PROGRA~1/QGIS33~1.6/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/hanisah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 94, in 
    from .utils import functions                               #Utility functions -> file functions.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1/QGIS33~1.6/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/hanisah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\utils\functions.py", line 26, in 
    from sklearn import svm
  File "C:\PROGRA~1/QGIS33~1.6/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hanisah\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages\sklearn\__init__.py", line 81, in 
    from . import __check_build  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1/QGIS33~1.6/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hanisah\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages\sklearn\__check_build\__init__.py", line 46, in 
    raise_build_error(e)
  File "C:\Users\hanisah\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages\sklearn\__check_build\__init__.py", line 31, in raise_build_error
    raise ImportError("""%s
ImportError: No module named 'sklearn.__check_build._check_build'
___________________________________________________________________________
Contents of C:\Users\hanisah\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages\sklearn\__check_build:
setup.py                  _check_build.cp37-win_amd64.pyd_check_build.cp39-win_amd64.pyd
__init__.py               __pycache__
___________________________________________________________________________
It seems that scikit-learn has not been built correctly.

If you have installed scikit-learn from source, please do not forget
to build the package before using it: run `python setup.py install` or
`make` in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.

Python version: 3.12.3 (main, Apr 14 2024, 17:21:43) [MSC v.1938 64 bit (AMD64)] 
QGIS version: 3.34.6-Prizren Prizren, 623828f5 

Python Path:
C:/PROGRA~1/QGIS33~1.6/apps/qgis-ltr/./python
C:/Users/hanisah/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/hanisah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.6/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS33~1.6\apps\grass\grass83\etc\python
C:\Users\hanisah\Documents
C:\Program Files\QGIS 3.34.6\bin\python312.zip
C:\PROGRA~1\QGIS33~1.6\apps\Python312\DLLs
C:\PROGRA~1\QGIS33~1.6\apps\Python312\Lib
C:\Program Files\QGIS 3.34.6\bin
C:\PROGRA~1\QGIS33~1.6\apps\Python312
C:\PROGRA~1\QGIS33~1.6\apps\Python312\Lib\site-packages
C:\PROGRA~1\QGIS33~1.6\apps\Python312\Lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.6\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.6\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/hanisah/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\hanisah\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages

**Comment by gustavowillam** [comment]
A new version of Smart-Map is available for QGIS versions 3.28 and 3.34. Please install the new version to fix the error described above.
