### ISSUE TITLE
Unable to execute SmartMap//AttributeError

### ISSUE THREAD

**Issue by nuhanb** [gustavowillam/SmartMapPlugin#73]
Hi, I managed to install the plugin, however I am unable to run the input layer when I clicked on "Import". It only loaded the attribute table without results. I could not further process it as the Grid, Interpolation and Management Zones panels are greyed out.

I am getting this error:

An error has occurred while executing Python code: 

AttributeError: module 'numpy' has no attribute 'float'. `np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here. The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:     https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'? 
Traceback (most recent call last):
  File "C:\Users/hanisah/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 1690, in pushButton_ImportQGIS_clicked
    self.data_outlier = np.array( self.data_outlier, dtype=np.float )
                                                           ^^^^^^^^
  File "C:\PROGRA~1\QGIS33~1.6\apps\Python312\Lib\site-packages\numpy\__init__.py", line 338, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?

Python version: 3.12.3 (main, Apr 14 2024, 17:21:43) [MSC v.1938 64 bit (AMD64)] 
QGIS version: 3.34.6-Prizren Prizren, 623828f5

**Comment by gustavowillam** [comment]
A new version of Smart-Map is available for QGIS versions 3.28 and 3.34. Please install the new version to fix the error described above.
