### ISSUE TITLE
plugin error

### ISSUE THREAD

**Issue by rilokex** [gustavowillam/SmartMapPlugin#74]
Hi, thank you for developing the plugin. I'm having some trouble interpolating data into a raster grid. When I click 'Interpolate,' QGIS shows the errors below:

![error](https://github.com/gustavowillam/SmartMapPlugin/assets/57588909/d4d81809-8395-4591-80ea-7ab57f4b528e)

Thank you!

**Comment by rilokex** [comment]
And,does anybody know how I can invert the color ramp? thank you!

**Comment by gustavowillam** [comment]
A new version of Smart-Map is available for QGIS versions 3.28 and 3.34. Please install the new version to fix the error described above.
