### ISSUE TITLE
Plugin installation error: classFactory() Method & KeyError: 'skip_parameter_validation'

### ISSUE THREAD

**Issue by AHernanC** [gustavowillam/SmartMapPlugin#75]
Hey there!
I installed the Plugin, but sadly can´t check the box for using it. It shows this error:

Konnte Erweiterung 'Smart_Map' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode 

KeyError: 'skip_parameter_validation' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.6/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Ayla/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\__init__.py", line 36, in classFactory
    from .Smart_Map import smart_map
  File "C:\PROGRA~1/QGIS33~1.6/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Ayla/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 94, in 
    from .utils import functions                               #Utility functions -> file functions.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1/QGIS33~1.6/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Ayla/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\utils\functions.py", line 27, in 
    from sklearn.model_selection import GridSearchCV
  File "C:\PROGRA~1/QGIS33~1.6/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS33~1.6\apps\Python312\Lib\site-packages\sklearn\model_selection\__init__.py", line 3, in 
    from ._plot import LearningCurveDisplay, ValidationCurveDisplay
  File "C:\PROGRA~1/QGIS33~1.6/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS33~1.6\apps\Python312\Lib\site-packages\sklearn\model_selection\_plot.py", line 7, in 
    from ._validation import learning_curve, validation_curve
  File "C:\PROGRA~1/QGIS33~1.6/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS33~1.6\apps\Python312\Lib\site-packages\sklearn\model_selection\_validation.py", line 29, in 
    from ..metrics import check_scoring, get_scorer_names
  File "C:\PROGRA~1/QGIS33~1.6/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS33~1.6\apps\Python312\Lib\site-packages\sklearn\metrics\__init__.py", line 68, in 
    from ._scorer import check_scoring, get_scorer, get_scorer_names, make_scorer
  File "C:\PROGRA~1/QGIS33~1.6/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS33~1.6\apps\Python312\Lib\site-packages\sklearn\metrics\_scorer.py", line 697, in 
    explained_variance_scorer = make_scorer(explained_variance_score)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS33~1.6\apps\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 184, in wrapper
    global_skip_validation = get_config()["skip_parameter_validation"]
                             ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'skip_parameter_validation'


Python-Version: 3.12.3 (main, Apr 14 2024, 17:21:43) [MSC v.1938 64 bit (AMD64)] 
QGIS-Version: 3.34.6-Prizren Prizren, 623828f5 

Python-Pfad:
C:/PROGRA~1/QGIS33~1.6/apps/qgis-ltr/./python
C:/Users/Ayla/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Ayla/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.6/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS33~1.6\apps\grass\grass83\etc\python
C:\Users\Ayla\Documents
C:\Program Files\QGIS 3.34.6\bin\python312.zip
C:\PROGRA~1\QGIS33~1.6\apps\Python312\DLLs
C:\PROGRA~1\QGIS33~1.6\apps\Python312\Lib
C:\Program Files\QGIS 3.34.6\bin
C:\PROGRA~1\QGIS33~1.6\apps\Python312
C:\PROGRA~1\QGIS33~1.6\apps\Python312\Lib\site-packages
C:\PROGRA~1\QGIS33~1.6\apps\Python312\Lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.6\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.6\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/Ayla/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users/Ayla/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing
C:\Users\Ayla\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing
C:\Users\Ayla\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs
C:\Users\Ayla\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages
D:/
C:\Users\Ayla\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages
C:\Users\Ayla\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages

![image](https://github.com/gustavowillam/SmartMapPlugin/assets/169474229/78d57fc2-5089-43f3-96fc-92694411ba08)


Additional info: I installed the scikit-learn first in the windows command prompt, and then copied the site-package from this folder:
C:\Users\Ayla\AppData\Roaming\Python\Python312\site-packages
into the QGIS python folder:
C:\Program Files\QGIS 3.34.6\apps\Python312\Lib\site-packages

Thanks for helping me out! 
Would love to use this tool.
Cheers, Ayla

**Comment by AHernanC** [comment]
I´m using these versions:

QGIS-Version | 3.34.6-Prizren | QGIS-Codeversion | 623828f5
-- | -- | -- | --
Qt-Version | 5.15.13
Python-Version | 3.12.3
GDAL-Version | 3.8.5
PROJ-Version | 9.4.0
EPSG-Registraturdatenbankversion | v11.004 (2024-02-24)
GEOS-Version | 3.12.1-CAPI-1.18.1
SQLite-Version | 3.45.1
PDAL-Version | 2.6.3
PostgreSQL-Client-Version | 16.2
SpatiaLite-Version | 5.1.0
QWT-Version | 6.2.0
QScintilla2-Version | 2.14.1
BS-Version | Windows 10 Version 2009
  |   |   |  
Aktive Python-Erweiterungen
beePen | 0.2.4
firstplugin | 0.1
gis4geology | 0.1
midvatten | 1.7.22
pluginbuilder3 | 3.2.1
plugin_reloader | 0.9.4
qgis_resource_sharing | 1.0.0
quick_map_services | 0.19.34
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS-Version
3.34.6-Prizren
QGIS-Codeversion
[623828f5](https://github.com/qgis/QGIS/commit/623828f5)
Qt-Version
5.15.13
Python-Version
3.12.3
GDAL-Version
3.8.5
PROJ-Version
9.4.0
EPSG-Registraturdatenbankversion
v11.004 (2024-02-24)
GEOS-Version
3.12.1-CAPI-1.18.1
SQLite-Version
3.45.1
PDAL-Version
2.6.3
PostgreSQL-Client-Version
16.2
SpatiaLite-Version
5.1.0
QWT-Version
6.2.0
QScintilla2-Version
2.14.1
BS-Version
Windows 10 Version 2009




Aktive Python-Erweiterungen
beePen
0.2.4
firstplugin
0.1
gis4geology
0.1
midvatten
1.7.22
pluginbuilder3
3.2.1
plugin_reloader
0.9.4
qgis_resource_sharing
1.0.0
quick_map_services
0.19.34
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

**Comment by rilokex** [comment]
Would you update the plugin to the newest version (1.4)?

**Comment by AHernanC** [comment]
I reinstalled it and restartet QGIS, that solved it!
Thank you!
