### ISSUE TITLE
Impossível carregar complemento 'Smart_Map' Devido a um erro ao chamar o método Class Factory()

### ISSUE THREAD

**Issue by patrick-jose-hudson** [gustavowillam/SmartMapPlugin#77]
Bom dia,

Estou com dificuldades para instalar o plugin smart-map.

Aparece a seguinte mensagem: Impossível carregar complemento 'Smart_Map' Devido a um erro ao chamar o método Class Factory().

Impossível carregar complemento 'Smart_Map' Devido a um erro ao chamar o método Class Factory(). 

ImportError: No module named 'sklearn.__check_build._check_build' ___________________________________________________________________________ Contents of C:\Users\Patrick\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages\sklearn\__check_build: setup.py                  _check_build.cp37-win_amd64.pyd__init__.py __pycache__ ___________________________________________________________________________ It seems that scikit-learn has not been built correctly. If you have installed scikit-learn from source, please do not forget to build the package before using it: run `python setup.py install` or `make` in the source directory. If you have used an installer, please check that it is suited for your Python version, your operating system and your platform. 
Traceback (most recent call last):
  File "C:\Users\Patrick\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages\sklearn\__check_build\__init__.py", line 44, in 
    from ._check_build import check_build  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1/QGIS33~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'sklearn.__check_build._check_build'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Patrick/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\__init__.py", line 36, in classFactory
    from .Smart_Map import smart_map
  File "C:\PROGRA~1/QGIS33~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Patrick/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 94, in 
    from .utils import functions                               #Utility functions -> file functions.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1/QGIS33~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Patrick/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\utils\functions.py", line 26, in 
    from sklearn import svm
  File "C:\PROGRA~1/QGIS33~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Patrick\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages\sklearn\__init__.py", line 81, in 
    from . import __check_build  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1/QGIS33~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Patrick\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages\sklearn\__check_build\__init__.py", line 46, in 
    raise_build_error(e)
  File "C:\Users\Patrick\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages\sklearn\__check_build\__init__.py", line 31, in raise_build_error
    raise ImportError("""%s
ImportError: No module named 'sklearn.__check_build._check_build'
___________________________________________________________________________
Contents of C:\Users\Patrick\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages\sklearn\__check_build:
setup.py                  _check_build.cp37-win_amd64.pyd__init__.py
__pycache__
___________________________________________________________________________
It seems that scikit-learn has not been built correctly.

If you have installed scikit-learn from source, please do not forget
to build the package before using it: run `python setup.py install` or
`make` in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.

Versão do Python: 3.12.4 (main, Jun 10 2024, 12:48:35) [MSC v.1938 64 bit (AMD64)] 
Versão do QGIS: 3.34.8-Prizren Prizren, 91642333 

Caminho do Python:
C:/PROGRA~1/QGIS33~1.8/apps/qgis-ltr/./python
C:/Users/Patrick/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Patrick/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.8/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS33~1.8\apps\grass\grass83\etc\python
C:\Users\Patrick\Documents
C:\Program Files\QGIS 3.34.8\bin\python312.zip
C:\PROGRA~1\QGIS33~1.8\apps\Python312\DLLs
C:\PROGRA~1\QGIS33~1.8\apps\Python312\Lib
C:\Program Files\QGIS 3.34.8\bin
C:\PROGRA~1\QGIS33~1.8\apps\Python312
C:\PROGRA~1\QGIS33~1.8\apps\Python312\Lib\site-packages
C:\PROGRA~1\QGIS33~1.8\apps\Python312\Lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.8\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.8\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/Patrick/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Patrick\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages
C:\Users\Patrick\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages
C:\Users\Patrick\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages
C:\Users\Patrick\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages

Poderia me ajudar?

**Comment by gustavowillam** [comment]
Bom dia Patrick! 
Está disponível uma nova versão do Smart-Map para as versões 3.28 e 3.34 do QGIS. Realize a instalação da nova versão para corrigir o erro acima descrito.
