### ISSUE TITLE
Erro ao clicar para interpolar (ValueError: invalid literal for int() with base 10: 'rgb:0.84313725490196079')

### ISSUE THREAD

**Issue by andresboo** [gustavowillam/SmartMapPlugin#82]
Ao clicar para interpolar aparece o erro de pyton abaixo:
Um erro ocorreu enquanto executava o código Python: 

ValueError: invalid literal for int() with base 10: 'rgb:0.84313725490196079' 
Traceback (most recent call last):
  File "C:\Users/andre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 3883, in pushButton_Krigagem_clicked
    Output_Layer_File_tiff = self.export_raster_to_qgis(Input_Table, Output_Layer_File_tiff, Output_Layer_Name, z_field)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/andre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 8528, in export_raster_to_qgis
    self.define_raster_color_ramp(rlayer, Output_Layer_Name)
  File "C:\Users/andre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 8599, in define_raster_color_ramp
    c1 = [ int(element) for element in rp['color1'].split(',') ]           #first color  Ex: red
           ^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'rgb:0.84313725490196079'

Versão do Python: 3.12.4 (main, Jun 10 2024, 12:48:35) [MSC v.1938 64 bit (AMD64)] 
Versão do QGIS: 3.38.1-Grenoble Grenoble, 3d4177afc6 

Caminho do Python:
C:\Users/andre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenTopography-DEM-Downloader
C:\Users/andre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Cadastral_Divisions-main
C:/PROGRA~1/QGIS33~1.1/apps/qgis/./python
C:/Users/andre/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/andre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~1.1\apps\grass\grass83\etc\python
C:\Users\andre\OneDrive\Desktop\ARQUIVOS QGIS\PROJETOS SALVOS
C:\PROGRA~1\QGIS33~1.1\bin\python312.zip
C:\PROGRA~1\QGIS33~1.1\apps\Python312\DLLs
C:\PROGRA~1\QGIS33~1.1\apps\Python312\Lib
C:\PROGRA~1\QGIS33~1.1\bin
C:\PROGRA~1\QGIS33~1.1\apps\Python312
C:\PROGRA~1\QGIS33~1.1\apps\Python312\Lib\site-packages
C:\PROGRA~1\QGIS33~1.1\apps\Python312\Lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.1\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.1\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/andre/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\andre\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
C:\Users\andre\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages
C:/Users/andre/OneDrive/Desktop/ARQUIVOS QGIS/PROJETOS SALVOS

**Comment by gustavowillam** [comment]
Utilize a versão estável (LTR) do QGIS 3.34. Esta versão que está utilizando (3.38) não é LTR e ainda está em fase esperimental.
