### ISSUE TITLE
ERROR WHEN MAKING KRIGING MAP (THE MAP IS DONE, BUT THE ERROR APPEARED IN A WINDOW)

### ISSUE THREAD

**Issue by maugaldemo** [gustavowillam/SmartMapPlugin#83]
An error has occurred while executing Python code: 

ValueError: invalid literal for int() with base 10: 'rgb:0.84313725490196079' 
Traceback (most recent call last):
  File "C:\Users/1002020071/AppData/Roaming/QGIS/QGIS3\profiles\MAU/python/plugins\Smart_Map\Smart_Map.py", line 3883, in pushButton_Krigagem_clicked
    Output_Layer_File_tiff = self.export_raster_to_qgis(Input_Table, Output_Layer_File_tiff, Output_Layer_Name, z_field)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/1002020071/AppData/Roaming/QGIS/QGIS3\profiles\MAU/python/plugins\Smart_Map\Smart_Map.py", line 8424, in export_raster_to_qgis
    self.define_raster_color_ramp(rlayer, Output_Layer_Name)
  File "C:\Users/1002020071/AppData/Roaming/QGIS/QGIS3\profiles\MAU/python/plugins\Smart_Map\Smart_Map.py", line 8599, in define_raster_color_ramp
    c1 = [ int(element) for element in rp['color1'].split(',') ]           #first color  Ex: red
           ^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'rgb:0.84313725490196079'

Python version: 3.12.5 (main, Aug  8 2024, 11:21:54) [MSC v.1938 64 bit (AMD64)] 
QGIS version: 3.38.2-Grenoble Grenoble, 130c432394 

Python Path:
C:\Users/1002020071/AppData/Roaming/QGIS/QGIS3\profiles\MAU/python/plugins\lftools
C:\Users/1002020071/AppData/Roaming/QGIS/QGIS3\profiles\MAU/python/plugins\contour
C:/OSGeo4W/apps/qgis/./python
C:/Users/1002020071/AppData/Roaming/QGIS/QGIS3\profiles\MAU/python
C:/Users/1002020071/AppData/Roaming/QGIS/QGIS3\profiles\MAU/python/plugins
C:/OSGeo4W/apps/qgis/./python/plugins
C:\OSGeo4W\apps\grass\grass84\etc\python
C:\OSGeo4W\bin
C:\OSGeo4W\bin\python312.zip
C:\OSGeo4W\apps\Python312\DLLs
C:\OSGeo4W\apps\Python312\Lib
C:\OSGeo4W\apps\Python312
C:\OSGeo4W\apps\Python312\Lib\site-packages
C:\OSGeo4W\apps\Python312\Lib\site-packages\win32
C:\OSGeo4W\apps\Python312\Lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/1002020071/AppData/Roaming/QGIS/QGIS3\profiles\MAU/python
C:\Users\1002020071\AppData\Roaming\QGIS\QGIS3\profiles\MAU\python\plugins\mmqgis/forms
C:\Users\1002020071\AppData\Roaming\QGIS\QGIS3\profiles\MAU\python\plugins\qfieldsync\libqfieldsync.whl
C:/Users/1002020071/Documents/CONSULTORIAS/2024/DAPASA
[An error has occurred while executi.txt](https://github.com/user-attachments/files/16741532/An.error.has.occurred.while.executi.txt)

**Comment by gustavowillam** [comment]
Your version of QGIS (3.38) is not LTR (Long Term Release). Please use Smart-Map with stable versions of QGIS (3.28 or 3.34 (https://www.qgis.org/downloads/QGIS-OSGeo4W-3.34.10-1.msi)).

**Comment by maugaldemo** [comment]
Thank for your answer.   I found that.  I install the last LTR version and everything works fine.

Ovrigado

Ing. Agr. Marco Antonio Ugalde Morales
Certificador de Uso Conforme #80
CIAGRO #1046
Especialista en Cartografía y Clasificación de Suelos IGAC COLOMBIA
M.Sc. Universidad de Costa Rica
________________________________
De: Gustavo Willam ***@***.***>
Enviado: lunes, 26 de agosto de 2024 16:05
Para: gustavowillam/SmartMapPlugin ***@***.***>
Cc: maugaldemo ***@***.***>; Author ***@***.***>
Asunto: Re: [gustavowillam/SmartMapPlugin] ERROR WHEN MAKING KRIGING MAP (THE MAP IS DONE, BUT THE ERROR APPEARED IN A WINDOW) (Issue #83)


Your version of QGIS (3.38) is not LTR (Long Term Release). Please use Smart-Map with stable versions of QGIS (3.28 or 3.34 (https://www.qgis.org/downloads/QGIS-OSGeo4W-3.34.10-1.msi)).

**Comment by zzzzzzzz-byte** [comment]
Hi, I use the LTR QGIS version 3.44.8-Solothurn Solothurn and my python version is 3.12.13 (main, Mar  5 2026, 15:14:54), and I run into the same issue.
