### ISSUE TITLE
Impossível carregar complemento 'Smart_Map' 

### ISSUE THREAD

**Issue by RafaelSmirne** [gustavowillam/SmartMapPlugin#9]
Uso o QGIS 3.16.9 e está aparecendo esse erro após a instalação, sabe o que posso fazer para resolver?

Impossível carregar complemento 'Smart_Map' Devido a um erro ao chamar o método Class Factory(). Consulte o registro de mensagens (Erro Python) para mais detalhes.

ImportError: No module named 'sklearn._check_build._check_build' __________________________________________________________________________ Contents of C:/Users/rafael.smirne/AppData/Roaming/QGIS/QGIS3/profiles/default/python/site-packages\sklearn\_check_build: setup.py                  _check_build.cp37-win_amd64.pyd__init__.py __pycache_ _________________________________________________________________________ It seems that scikit-learn has not been built correctly. If you have installed scikit-learn from source, please do not forget to build the package before using it: run `python setup.py install` or `make` in the source directory. If you have used an installer, please check that it is suited for your Python version, your operating system and your platform. 

Versão do Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] 
Versão do QGIS: 3.16.9-Hannover Hannover, 9f8d2f7942

**Comment by andre5620** [comment]
Estou encontrando esse mesmo erro na versão 'Versão do QGIS 3.10.0-A CoruÃ±a'. Há alguma versão a recomendar estavel ?

**Comment by gustavowillam** [comment]
Olá Rafael. O plugin funciona apenas para o QGIS versão 64 bits. A versão que vc instalou é 32 bits. 
Utilize uma versão do QGIS 64 bits. 
André e Rafael, sugiro a última versão LTR (3.16.9) https://qgis.org/downloads/QGIS-OSGeo4W-3.16.9-1-Setup-x86_64.exe
Opte pelo instalador com extensão .exe

**Comment by RafaelSmirne** [comment]
Obrigado Gustavo, agora deu certo!

Att,

Rafael

Em ter., 10 de ago. de 2021 às 18:22, Gustavo Willam <
***@***.***> escreveu:

**Comment by andre5620** [comment]
Realmente deu certo, obrigado Gustavo !

Atenciosamente,
